config/routes.rb
MikeFalkowski::Application.routes.draw do
  devise_for :users, :skip => :registrations

  resources :posts, :teches, :works
  root :to => 'home#index'

	match 'splinko' => 'home#splinko'
	match 'pnoise' => 'home#pnoise'
	
	

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body, :image
  has_attached_file :image, :styles => { :large => "300x300>", :thumb => "150x150>" }
  
  def as_json(options={})
    hash = super(options)
    hash.merge!(
                'image_thumb_url' => image.url(:thumb),
                'image_large_url' => image.url(:large)
                )
    hash
  end
end

app/models/tech.rb
class Tech < ActiveRecord::Base
  attr_accessible :title, :link, :image
  has_attached_file :image, :styles => { :large => "200x200>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :body, :image, :link, :title
  has_attached_file :image, :styles => { :large => "400x400>", :thumb => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		render "index"
	end
	
	def splinko
		render "splinko", :layout => false
	end
	
	def pnoise
		render "pnoise", :layout => false
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	respond_to :json
	before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
	
	def index
		@posts = Post.all
		respond_to do |format|
    		format.html  { render "admin", :layout => 'admin'}
    		format.json  { render :json => @posts.reverse }
  		end
	end
	
	def edit
		@post = Post.find(params[:id])
		render "edit", :layout => 'admin'
	end
	
	def show
		@post = Post.find(params[:id])
		respond_to do |format|
    		format.html  { render "show", :layout => 'admin'}
    		format.json  { render :json => @post }
  		end
	end
	
	def new
	 	@post = Post.new
	 	render "new", :layout => 'admin'
	end
	
	def create
		@post = Post.new(params[:post])
		if @post.save
			flash[:notice] = 'Post was successfully created.' 
			redirect_to :action => 'index'
		else
			flash[:notice] = 'Problem.'
			redirect_to :action => 'index'
		end
	end
	
	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(params[:post])
			flash[:notice] = 'Post was successfully updated.'
			redirect_to :action => 'index'
		else
			flash[:notice] = 'Error :('
			redirect_to :action => 'index'
		end
	end
	
	def destroy
		@post = Post.find(params[:id])
	  	@post.destroy
	  	flash[:notice] = 'Post Deleted'
		redirect_to :action => 'index'
	end
end

app/controllers/teches_controller.rb
class TechesController < ApplicationController

	respond_to :json
	before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
	
	def index
		@teches = Tech.all
		respond_to do |format|
    		format.html  { render "admin", :layout => 'admin'}
    		format.json  { render :json => @teches }
  		end
	end
	
	def edit
		@tech = Tech.find(params[:id])
		render "edit", :layout => 'admin'
	end
	
	def show
		@tech = Tech.find(params[:id])
		respond_to do |format|
    		format.html  { render "show", :layout => 'admin'}
    		format.json  { render :json => @tech }
  		end
	end
	
	def new
	 	@tech = Tech.new
	 	render "new", :layout => 'admin'
	end
	
	def create
		@tech = Tech.new(params[:tech])
		if @tech.save
			flash[:notice] = 'Tech was successfully created.' 
			redirect_to :action => 'index'
		else
			flash[:notice] = 'Problem.'
			redirect_to :action => 'index'
		end
	end
	
	def update
		@tech = Tech.find(params[:id])
		if @tech.update_attributes(params[:tech])
			flash[:notice] = 'Tech was successfully updated.'
			redirect_to :action => 'index'
		else
			flash[:notice] = 'Error :('
			redirect_to :action => 'index'
		end
	end
	
	def destroy
		@tech = Tech.find(params[:id])
	  	@tech.destroy
	  	flash[:notice] = 'Tech Deleted'
		redirect_to :action => 'index'
	end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
	respond_to :json
	before_filter :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
	
	def index
		@works = Work.all
		respond_to do |format|
    		format.html  { render "admin", :layout => 'admin'}
    		format.json  { render :json => @works }
  		end
	end
	
	def edit
		@work = Work.find(params[:id])
		render "edit", :layout => 'admin'
	end
	
	def show
		@work = Work.find(params[:id])
		respond_to do |format|
    		format.html  { render "show", :layout => 'admin'}
    		format.json  { render :json => @work }
  		end
	end
	
	def new
	 	@work = Work.new
	 	render "new", :layout => 'admin'
	end
	
	def create
		@work = Work.new(params[:work])
		if @work.save
			flash[:notice] = 'Work was successfully created.' 
			redirect_to :action => 'index'
		else
			flash[:notice] = 'Problem.'
			redirect_to :action => 'index'
		end
	end
	
	def update
		@work = Work.find(params[:id])
		if @work.update_attributes(params[:work])
			flash[:notice] = 'Work was successfully updated.'
			redirect_to :action => 'index'
		else
			flash[:notice] = 'Error :('
			redirect_to :action => 'index'
		end
	end
	
	def destroy
		@work = Work.find(params[:id])
	  	@work.destroy
	  	flash[:notice] = 'Work Deleted'
		redirect_to :action => 'index'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/teches_helper.rb
module TechesHelper
end

app/helpers/work_helper.rb
module WorkHelper
end

app/views/home/pnoise.html.erb
<head>
	<title>Perlin Lines</title>
	<%= javascript_include_tag "processing" %>
	
</head>
<body>
	<canvas data-processing-sources="/processing/pnoise.pde" id="canvas"></canvas>

	<script>
		document.getElementById('canvas').ondragstart = function() { return false; };
	</script>
</body>

app/views/home/splinko.html.erb
<head>
	<title>sPlinko</title>
	<%= javascript_include_tag "processing" %>
	
</head>
<body>
	<p>Left click above the pegs. Catch as many as you can.</p>
	<canvas data-processing-sources="/processing/plink.pde" id="canvas"></canvas>

	<script>
		document.getElementById('canvas').ondragstart = function() { return false; };
	</script>
</body>

app/views/layouts/admin.html.erb
<head>
	<title>Poopy Admin</title>
	 <%= stylesheet_link_tag    "application", :media => "all" %>
	 <%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>
</head>
<body>
<div class="row span10">
  <% if user_signed_in? %>
		Signed in as <%= current_user.email %>. Not you?
		<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
		<div class="row span10">
			<%= link_to 'Site ',  root_path %>
			<%= link_to 'Works ',  works_path %>
			<%= link_to 'Posts ',  posts_path %>
			<%= link_to 'Teches ',  teches_path %>
		</div>
		<p class="alert"><%= notice %></p>
		<%= yield %>
	<% else %>
		<%= link_to "sign in", new_user_session_path %>
		<h3>Did you want <%= link_to 'This? ',  root_path %>
  <% end %>
</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="myApp">
<head>
  <title>Mike Falkowski</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<div id="linearBg2"><a href="#"><%= image_tag "falko_logo.png" %></a></div>
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="span2">
				<ul class="nav nav-tabs nav-stacked">
					<li><a href="#/about">About Me</a></li>
					<li><a href="#/work">My Projects</a></li>
				</ul>

			</div>

			<div class="span10" ng-view>

			</div>
		</div>
	</div>


</body>
</html>

app/views/layouts/devise.html.erb
<head>
	<title>Poopy Admin</title>
	 <%= stylesheet_link_tag    "application", :media => "all" %>
	 <%= javascript_include_tag "application" %>
	<%= csrf_meta_tag %>
</head>
<body>
	<div class="span10">
		<%= yield %>
	</div>
</body>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <%= f.file_field :image %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/admin.html.erb
	<%= link_to 'New', new_post_path %>
	<% @posts.each do |p|%>
	<div class="row span10">
		<h4><%= p.title %></h4>
		<p><%= p.id %></p>
		<p><%= p.body %></p>
		<p><%= p.image.url %></p>
		<%= link_to 'Edit', edit_post_path(p) %>
		<%= link_to 'Destroy', p, :confirm => 'Are you sure?', :method => :delete %>
	</div>
	<% end %>

app/views/posts/edit.html.erb
<div class="span10">
<h1>Editing post</h1>
 
<%= render 'form' %>
</div>

app/views/posts/new.html.erb
<div class="span10">
<h1>New post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
	<h4><%= @post.title %></h4>
	<p><%= @post.body %></p>
	<p><%= @post.image %></p>
	</br>

app/views/teches/_form.html.erb
<%= form_for(@tech) do |f| %>
  <% if @tech.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@tech.errors.count, "error") %> prohibited
        this post from being saved:</h2>
    <ul>
    <% @tech.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>

  <%= f.file_field :image %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teches/admin.html.erb
	<%= link_to 'New', new_tech_path %>
	<% @teches.each do |t|%>
	<div class="row span10">
		<h4><%= t.title %></h4>
		<p><%= t.image.url %></p>
		<%= link_to 'Edit', edit_tech_path(t) %>
		<%= link_to 'Destroy', t, :confirm => 'Are you sure?', :method => :delete %>
	</div>
	<% end %>

app/views/teches/edit.html.erb
<h1>Editing tech</h1>
 
<%= render 'form' %>

app/views/teches/new.html.erb
<h1>New tech</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', teches_path %>

app/views/teches/show.html.erb
	<h4><%= @tech.title %></h4>

	<p><%= @tech.image %></p>
	</br>

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@work.errors.count, "error") %> prohibited
        this post from being saved:</h2>
    <ul>
    <% @work.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
   <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <%= f.file_field :image %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/works/admin.html.erb
	<%= link_to 'New', new_work_path %>
	<% @works.each do |w|%>
	<div class="row span10">
		<h4><%= w.title %></h4>
		<p><%= w.body %></p>
		<p><%= w.image.url %></p>
		<%= link_to 'Edit', edit_work_path(w) %>
		<%= link_to 'Destroy', w, :confirm => 'Are you sure?', :method => :delete %>
	</div>
	<% end %>

app/views/works/edit.html.erb
<h1>Editing work</h1>
 
<%= render 'form' %>

app/views/works/new.html.erb
<h1>New work</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
	<h4><%= @work.title %></h4>
	<p><%= @work.body %></p>
	<p><%= @work.image %></p>
	</br>